---
title: "Visualisation of evolution of novel coronavirus"
author: "Marcelo Avila"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# for dates in english 
sys_time_local_old <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "en_US.UTF-8")

# avoid scientific notation
options(scipen = 999)
```

# load libraries

```{r libs, include=FALSE}
library(tidyverse)
library(ggsci)
library(countrycode)
```

# load data 

```{r data, message=FALSE, warning=FALSE, include=FALSE}
url_path <- "https://covid.ourworldindata.org/data/full_data.csv"
df <- read_csv(url_path) %>%
  pivot_longer(-c(location, date), names_to = "category") %>% 
  mutate(value = if_else(is.na(value), 0, value))

pop_data <- readr::read_csv("../data/pop_data.csv",
                            #locale = locale(grouping_mark = "."),
                            col_types = cols(Density = col_skip(), 
                                             GrowthRate = col_skip(),
                                             WorldPercentage = col_skip(), 
                                             area = col_skip(),
                                             dropdownData = col_skip(), 
                                             rank = col_skip()))

df <- left_join(df, pop_data, by = c("location"="name")) %>%
  mutate(pop2020 = pop2020 * 1e3, 
         value_per_100k_inhab = value / pop2020 * 1e5)
```

```{r relabel}
cat_labels <- c("daily cases", "daily deaths",
                "cumulative cases", "cumulative deaths")
df <- df %>% mutate(category = factor(category, 
                                labels = cat_labels), 
                    continent=countrycode(location,
                                          origin = "country.name",
                                          destination = "continent"))
```



There is data for `r df$location %>% unique %>% length - 2` countries. 
The last update was on `r tail(df$date, 1) %>% format("%d of %B")`

```{r inspect}
head(df)
```


```{r functions}
# for thousand separator for plotting
fun_dot <- function(x) format(x, big.mark = " ",
                              scientific = FALSE,
                              decimal.mark = ".")

# negative in
`%!in%` <- Negate(`%in%`)

# y scale
log10_minor_break = function (...){
  function(x) {
    minx         = floor(min(log10(x), na.rm=T))-1;
    maxx         = ceiling(max(log10(x), na.rm=T))+1;
    n_major      = maxx-minx+1;
    major_breaks = seq(minx, maxx, by=1)
    minor_breaks = 
      rep(log10(seq(1, 9, by=1)), times = n_major)+
      rep(major_breaks, each = 9)
    return(10^(minor_breaks))
  }
}
```


# Cumulative Cases for Selected Countries

```{r, warning=FALSE}
sel_category <- "cumulative cases"  # new cases, new deaths,
                                    # cumulative cases, cumulative deaths
selected_countries <- c("Germany",
                        "Italy",
                        "United Kingdom",
                        "Brazil",
                        "China",
                        "Spain",
                        "South Korea", 
                        "United States")

df %>% 
  # wrangle
  filter(location %in% selected_countries, category==sel_category) %>% 
  mutate(
    location=fct_reorder2(location, date, value),
    label = ifelse(date == "2020-02-29", #max(date),
                        as.character(location), 
                        NA_character_)) %>% 

  # plot
  ggplot(aes(x=date, y=value, color=location)) + 
  geom_point(aes(shape="o")) +
  geom_line(aes(linetype=location)) + 
  
  # labels
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = -1, nudge_y = 1/10,
                            na.rm = TRUE) +
  # legend and scales
  scale_y_log10(name="(log scale)", labels=fun_dot, 
                breaks=10^(0:9),
                #minor_breaks=log10_minor_break()
                minor_breaks=(1 * 1.33333^(0:10000))
                ) + 
  scale_x_date(date_breaks = "1 week", 
               date_labels="%d%b") +
  ggsci::scale_color_aaas() +
  theme(legend.position = "none", 
        axis.title.y = element_blank()) 
```


# Normalized comparison 
```{r}
df$continent %>% unique()
df$category %>% unique() %>% as.character()
```

```{r eval=FALSE, include=FALSE}
sel_continent = "Asia"
sel_category = "cumulative cases"
threshold <- 10
singular_category <- scan(text = sel_category, what = "", quiet=TRUE)[2] %>% 
  substr(1, nchar(.)-1)

df %>%
  filter(category == sel_category, 
         continent == sel_continent) %>% 
  group_by(location) %>% 
  filter(value>=threshold) %>% 
  mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
  ungroup(location) %>% 
  arrange(date_shift) %>% 
  # mutate for legend ordering and ggrepel postioning
  mutate(location=fct_reorder2(location, date_shift, value), 
         # for ggrepel
         label = ifelse(date == max(date),
                        as.character(location), 
                        NA_character_)) %>% 
  ggplot(aes(x=date_shift, y=value, colour=location)) + 
  # geoms
  geom_point() +
  geom_line(aes(linetype=location)) + 
  
  # ggrepel 
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = 0,
                            na.rm = TRUE) +
 
  # legend and scales
  scale_y_log10(
    name = paste(sel_category, "(log scale)"), labels=fun_dot, 
    breaks = 10^(0:9),
    minor_breaks=log10_minor_break()) + 
  scale_x_continuous(
    name = paste0("Days past ", threshold, "th ", singular_category),
    breaks = seq(0, 1e5, 7),
    minor_breaks = 1:1e3) +
  scale_color_grey(start = 0, end = .3) +
  
  theme(legend.position = "none", 
        axis.title.y = element_blank()) + 
  #title
  ggtitle(paste("Evolution of novel coronavirus in", sel_continent), 
          subtitle = paste(sel_category, "(log scale)"))

```

```{r}
make_plot <- function(dta, sel_category="cumulative cases",
                      sel_continent="Europe",
                      sel_country=NULL, 
                      threshold=100) {
  
  # extract singular form of category
  singular_category <- scan(text = sel_category, what = "", quiet=TRUE)[2] %>% 
    substr(1, nchar(.)-1)
  
  sel_plot_title <- ifelse(length(sel_continent)>1,
                                yes = "selected continents",
                                no = sel_continent)

  if (!is.null(sel_country)) {
    dta <- dta %>% filter(location %in% sel_country)
    sel_continent <- unique(dta$continent)
    
    sel_plot_title <- ifelse(length(sel_country)>1,
                             yes = "selected countries",
                             no = sel_country)
  }
  
  
  dta %>% 
    filter(category == sel_category, 
           continent %in% sel_continent) %>% 
    group_by(location) %>% 
    filter(value>=threshold) %>% 
    mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
    ungroup(location) %>% 
    arrange(date_shift) %>% 
    # mutate for legend ordering and ggrepel postioning
    mutate(location=fct_reorder2(location, date_shift, value), 
           # for ggrepel
           label = ifelse(date == max(date),
                          as.character(location), 
                          NA_character_)) %>%
    # plot  
    ggplot(aes(x=date_shift, y=value, colour=location)) + 
    # geoms
    geom_point() +
    geom_line(aes(linetype=location, colour=location)) + 
    #scale_color_grey(start = 0, end = .3) +
    
    # ggrepel 
    ggrepel::geom_label_repel(
      aes(label = label), nudge_x = 1, na.rm = TRUE) +
    
    # legend and scales
    scale_y_log10(
      name = paste(sel_category, "(log scale)"),
      labels=fun_dot, breaks = 10^(0:9), minor_breaks=log10_minor_break()) + 
    scale_x_continuous(
      name = paste0("Days past since ", threshold, "th ", singular_category),
      breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) +
    
    theme(legend.position = "none", axis.title.y = element_blank()) + 
    #title
    ggtitle(paste("Evolution of novel coronavirus in", sel_plot_title), 
            subtitle = paste(sel_category, "(log scale)"))
}
```
```{r}

countries <- c("Brazil", "United States",
               "Italy", "Iran", "South Korea", 
               "Cingapure", "Japan", "Australia", 
               "India")
#countries <- df$location %>% unique
conts <- "Europe"

make_plot(df, sel_country = countries, threshold = 1,
          sel_category = "cumulative deaths")
make_plot(df, sel_continent = conts, threshold = 10,
          sel_category = "cumulative deaths")

```


```{r}
categories <- df$category %>% unique() %>% as.character() %>% purrr::set_names()
continents <- df$continent %>% unique() %>% as.character() %>% purrr::set_names()

plots_categ <- purrr::map(categories, ~make_plot(df, sel_category = .x, 
                                                 threshold = 25))
plots_conts <- purrr::map(continents, ~make_plot(df, sel_continent = .x, 
                                                 sel_category = "cumulative deaths",
                                                 threshold = 1))

plots_categ
plots_conts
```


```{r eval=FALSE, include=FALSE}



th <- 50
df_cnt %>% 
  filter(location %!in% c("International",  "World")) %>% 
  group_by(location) %>% 
  mutate(label = ifelse(date == max(date),
                        as.character(location), 
                        NA_character_)) %>% 
  ggplot(aes(x=date, y=value, colour=location)) + 
  geom_point() +
  geom_line() + 
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = 1,
                            na.rm = TRUE) + 
  theme(legend.position = "none") + 
  scale_y_log10(category="Infections (log scale)", labels=fun_dot, 
                breaks=2^(0:20) * 1) + 
  scale_x_continuous(category=paste0("Days since ", threshold, "th death"), 
                     breaks=seq(0, 1e3, 7)) + 
  ggtitle("Comparison of COVID-19 fatalities by country")



pop_data <- readr::read_csv("./data/pop_data.csv",
                            #locale = locale(grouping_mark = "."),
                            col_types = cols(Density = col_skip(), 
                                             GrowthRate = col_skip(),
                                             WorldPercentage = col_skip(), 
                                             area = col_skip(),
                                             dropdownData = col_skip(), 
                                             rank = col_skip()))

threshold = 0.01
df_pop <- left_join(df, pop_data, by = c("location"="category")) %>%
  mutate(pop2020 = pop2020 * 1e3)
df_pop %>% mutate(pop_value = value / pop2020 * 1e5) %>%
  filter(category==category) %>% 
  group_by(location) %>% 
  mutate(check = if_else(pop_value>=threshold, 1, 0)) %>% 
  filter(check==1) %>% group_by(location) %>% 
  mutate(date = ave(1:length(location), df$location, FUN = seq_along)) %>% 
  ungroup(location) %>% arrange(date) %>% 
  #filter(location %in% selected_countries) %>% 
  mutate(location=fct_reorder2(location, date, pop_value)) %>% 
  
  filter(location %!in% c("International",  "World")) %>% 
  group_by(location) %>% 
  mutate(label = ifelse(date == max(date),
                        as.character(location), 
                        NA_character_)) %>% 
  ggplot(aes(x=date, y=pop_value, colour=location)) + 
  geom_point() + geom_line() + 
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = 1,
                            na.rm = TRUE) + 
  theme(legend.position = "none") + 
  scale_y_log10(category="(log scale)", labels=fun_dot, 
                breaks=2^(0:20) / 1000 ) + 
  scale_x_continuous(category=paste0("Days since ", th, "th case"), 
                     breaks=seq(0, 1e3, 7)) + 
  ggtitle("Fatalities by 100.000 inhabitants")


```


```{r reset_options, message=TRUE, warning=TRUE, include=FALSE}
Sys.setlocale("LC_TIME", sys_time_local_old)
```

