---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```


# parameters 

```{r}
nr_infected_berlin <- c(0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 9, 15, 24, 28, 40, 48, 90, 137, 174)
date <- c("2020-02-24", "2020-02-25", "2020-02-26", "2020-02-27", "2020-02-28", "2020-02-29",
          "2020-03-01", "2020-03-02", "2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06",
          "2020-03-07", "2020-03-08", "2020-03-09", "2020-03-10", "2020-03-11", "2020-03-12",
          "2020-03-13") %>% as.Date()

df <- data.frame(date=date,
                 nr_infected_berlin=nr_infected_berlin)

barplot(height = df$nr_infected_berlin, names.arg = df$date)
```

# projections

## constant growth rate

```{r, warning=F}
avg_gr <- ifelse(df$nr_infected_berlin>0, df$nr_infected_berlin, NA)
growth_rate <- diff(avg_gr) %>% mean(x = ., na.rm = T)/100 + 1
growth_rate <- 1.20
weeks <- 8
t <- 1:(7*weeks) # in days
df_proj <- data.frame(
  date=tail(df$date, 1) + t,
  nr_infected_berlin=tail(df$nr_infected_berlin, 1) * growth_rate ^ t
)

df_combined <- bind_rows(df, df_proj)
df_combined <- df_combined %>% 
  mutate(
    p1 = c(rep(NA, nrow(df)),
           tail(df$nr_infected_berlin, 1) * 1.1 ^ t),
    p2 = c(rep(NA, nrow(df)),
           tail(df$nr_infected_berlin, 1) * 1.2 ^ t),
    p3 = c(rep(NA, nrow(df)),
           tail(df$nr_infected_berlin, 1) * 1.3 ^ t)
  )
```


```{r, warning=F}
matplot(x = as.Date(df_combined$date)-Sys.Date(),
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> pop_size <- 80 * 1e6
> 
> T <- 30 * 3
> N <- rep(NA, T)
> N[1] <- 3000
> 
> 
> con <- 1 + 
+ for (t in 2:T) {
+   # print(t)
+   # print(N[t-1])
+   N[t] <- con * (1 - (N[t-1]/pop_size)) * N[t-1]
+ }
Error in con : object 'con' not found
> library(tidyverse)
Registered S3 method overwritten by 'dplyr':
  method           from
  print.rowwise_df     
── Attaching packages ─────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
✓ ggplot2 3.3.0     ✓ purrr   0.3.3
✓ tibble  2.1.3     ✓ dplyr   0.8.5
✓ tidyr   1.0.2     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.4.0
── Conflicts ────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
> nr_infected_berlin <- c(0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 9, 15, 24, 28, 40, 48, 90, 137, 174)
> date <- c("2020-02-24", "2020-02-25", "2020-02-26", "2020-02-27", "2020-02-28", "2020-02-29",
+           "2020-03-01", "2020-03-02", "2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06",
+           "2020-03-07", "2020-03-08", "2020-03-09", "2020-03-10", "2020-03-11", "2020-03-12",
+           "2020-03-13") %>% as.Date()
> 
> df <- data.frame(date=date,
+                  nr_infected_berlin=nr_inf)
Error in data.frame(date = date, nr_infected_berlin = nr_inf) : 
  object 'nr_inf' not found
> avg_gr <- ifelse(df$nr_infected_berlin>0, df$nr_infected_berlin, NA)
Error in df$nr_infected_berlin : 
  object of type 'closure' is not subsettable
> library(tidyverse)
> nr_infected_berlin <- c(0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 9, 15, 24, 28, 40, 48, 90, 137, 174)
> date <- c("2020-02-24", "2020-02-25", "2020-02-26", "2020-02-27", "2020-02-28", "2020-02-29",
+           "2020-03-01", "2020-03-02", "2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06",
+           "2020-03-07", "2020-03-08", "2020-03-09", "2020-03-10", "2020-03-11", "2020-03-12",
+           "2020-03-13") %>% as.Date()
> 
> df <- data.frame(date=date,
+                  nr_infected_berlin=nr_inf)
Error in data.frame(date = date, nr_infected_berlin = nr_inf) : 
  object 'nr_inf' not found
> nr_infected_berlin <- c(0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 9, 15, 24, 28, 40, 48, 90, 137, 174)
> date <- c("2020-02-24", "2020-02-25", "2020-02-26", "2020-02-27", "2020-02-28", "2020-02-29",
+           "2020-03-01", "2020-03-02", "2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06",
+           "2020-03-07", "2020-03-08", "2020-03-09", "2020-03-10", "2020-03-11", "2020-03-12",
+           "2020-03-13") %>% as.Date()
> 
> df <- data.frame(date=date,
+                  nr_infected_berlin=nr_infected_berlin)
> 
> barplot(height = df$nr_infected_berlin, names.arg = df$date)
> avg_gr <- ifelse(df$nr_infected_berlin>0, df$nr_infected_berlin, NA)
> growth_rate <- diff(avg_gr) %>% mean(x = ., na.rm = T)/100 + 1
> growth_rate <- 1.20
> weeks <- 8
> t <- 1:(7*weeks) # in days
> df_proj <- data.frame(
+   date=tail(df$date, 1) + t,
+   nr_infected_berlin=tail(df$nr_infected_berlin, 1) * growth_rate ^ t
+ )
> 
> df_combined <- bind_rows(df, df_proj)
> df_combined <- df_combined %>% 
+   mutate(
+     p1 = c(rep(NA, nrow(df)),
+            tail(df$nr_infected_berlin, 1) * 1.1 ^ t),
+     p2 = c(rep(NA, nrow(df)),
+            tail(df$nr_infected_berlin, 1) * 1.2 ^ t),
+     p3 = c(rep(NA, nrow(df)),
+            tail(df$nr_infected_berlin, 1) * 1.3 ^ t)
+   )
> matplot(x = as.Date(df_combined$date)-Sys.Date(),
+         y = dplyr::select(df_combined, -date),
+         log = "y", type="l")
> grid()
> pop_size <- 80 * 1e6
> 
> T <- 30 * 3
> N <- rep(NA, T)
> N[1] <- 3000
> 
> 
> con <- 1 + 
+ for (t in 2:T) {
+   # print(t)
+   # print(N[t-1])
+   N[t] <- con * (1 - (N[t-1]/pop_size)) * N[t-1]
+ }
Error in con : object 'con' not found
> matplot(x = as.Date(df_combined$date)-Sys.Date(),
+         y = dplyr::select(df_combined, -date),
+         log = "y", type="l")
> grid()
> pop_size <- 80 * 1e6
> 
> T <- 30 * 3
> N <- rep(NA, T)
> N[1] <- 3000
> 
> 
> con <- 1 + 
+ for (t in 2:T) {
+   # print(t)
+   # print(N[t-1])
+   N[t] <- con * (1 - (N[t-1]/pop_size)) * N[t-1]
+ }
Error in con : object 'con' not found
> pop_size <- 80 * 1e6
> 
> T <- 30 * 3
> N <- rep(NA, T)
> N[1] <- 3000
> 
> 
> con <- 1.2
> for (t in 2:T) {
+   # print(t)
+   # print(N[t-1])
+   N[t] <- con * (1 - (N[t-1]/pop_size)) * N[t-1]
+ }
> 
> plot(N, type="l")
> 
> knitr::opts_chunk
$get
function (name, default = FALSE, drop = TRUE) 
{
    if (default) 
        defaults = value
    if (missing(name)) 
        defaults
    else {
        if (drop && length(name) == 1) 
            defaults[[name]]
        else {
            setNames(defaults[name], name)
        }
    }
}
<bytecode: 0x55fd2697d5e8>
<environment: 0x55fd26974c10>

$set
function (...) 
{
    dots = resolve(...)
    if (length(dots)) 
        defaults <<- merge(dots)
    invisible(NULL)
}
<bytecode: 0x55fd2697c708>
<environment: 0x55fd26974c10>

$delete
function (keys) 
{
    for (k in keys) defaults[[k]] <<- NULL
}
<bytecode: 0x55fd2697bcc0>
<environment: 0x55fd26974c10>

$append
function (...) 
{
    dots = resolve(...)
    for (i in names(dots)) dots[[i]] <- c(defaults[[i]], dots[[i]])
    if (length(dots)) 
        defaults <<- merge(dots)
    invisible(NULL)
}
<bytecode: 0x55fd2697f150>
<environment: 0x55fd26974c10>

$merge
function (values) 
merge_list(defaults, values)
<bytecode: 0x55fd2697e078>
<environment: 0x55fd26974c10>

$restore
function (target = value) 
defaults <<- target
<bytecode: 0x55fd269817e0>
<environment: 0x55fd26974c10>

Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
  there is no package called ‘knitr::opts_chunk’
> ?knitr::opts_chunk
> str(knitr::opts_chunk$get())
List of 53
 $ eval         : logi TRUE
 $ echo         : logi TRUE
 $ results      : chr "markup"
 $ tidy         : logi FALSE
 $ tidy.opts    : NULL
 $ collapse     : logi FALSE
 $ prompt       : logi FALSE
 $ comment      : chr "##"
 $ highlight    : logi TRUE
 $ strip.white  : logi TRUE
 $ size         : chr "normalsize"
 $ background   : chr "#F7F7F7"
 $ cache        : logi FALSE
 $ cache.path   : chr "cache/"
 $ cache.vars   : NULL
 $ cache.lazy   : logi TRUE
 $ dependson    : NULL
 $ autodep      : logi FALSE
 $ cache.rebuild: logi FALSE
 $ fig.keep     : chr "high"
 $ fig.show     : chr "asis"
 $ fig.align    : chr "default"
 $ fig.path     : chr "figure/"
 $ dev          : NULL
 $ dev.args     : NULL
 $ dpi          : num 72
 $ fig.ext      : NULL
 $ fig.width    : num 7
 $ fig.height   : num 7
 $ fig.env      : chr "figure"
 $ fig.cap      : NULL
 $ fig.scap     : NULL
        y = dplyr::select(df_combined, -date),
        log = "y", type="l")
grid()
```

```{r, warning=F}
pop_size <- 80 * 1e6

T <- 30 * 3
N <- rep(NA, T)
N[1] <- 3000


con <- 1.2
for (t in 2:T) {
  # print(t)
  # print(N[t-1])
  N[t] <- con * (1 - (N[t-1]/pop_size)) * N[t-1]
}

plot(N, type="l")

```




