---
title: Evolution of COVID-19 Pandemic across countries and Continents
author: Marcelo Avila
date: '2020-03-25'
slug: evolution-of-covid-19-pandemic-across-countries-and-continents
categories:
  - visualization
tags:
  - corona
  - covid-19
  - ggplot
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# for dates in english 
sys_time_local_old <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "en_US.UTF-8")

# avoid scientific notation
options(scipen = 999)
```

# load libraries

```{r libs, include=FALSE}
library(tidyverse)
library(ggsci)
library(countrycode)
library(readxl)
library(httr)
library(lubridate)
```

# load data 

```{r load data, message=FALSE, warning=FALSE, include=FALSE}

if (hour(Sys.time()) < 8) {
  time <- (Sys.Date() - lubridate::days(1)) %>% format("%Y-%m-%d")
} else {
  time <- Sys.Date() %>% format("%Y-%m-%d")
}
url <- paste("https://www.ecdc.europa.eu/sites/default/files/documents/",
             "COVID-19-geographic-disbtribution-worldwide-",
             time, ".xlsx", sep = "")

#download the dataset from the website to a local temporary file
GET(url, authenticate(":", ":", type="ntlm"),
    write_disk(tf <- tempfile(fileext = ".xlsx", pattern = "covid_")))

#read the Dataset sheet into “R”
df <- read_excel(tf) %>% 
  rename(Daily_Cases = cases, 
         Daily_Deaths = deaths,
         Location = countriesAndTerritories) %>% 
  arrange(Location, dateRep)
df$Location <- df$Location %>% 
  str_replace_all("_", " ") %>% 
  str_to_lower() %>% 
  tools::toTitleCase()
```

# wrangle 

```{r gen cum, message=FALSE, warning=FALSE}
df <- df %>% group_by(Location) %>% 
  mutate(Cum_Cases = cumsum(Daily_Cases), 
         Cum_Deaths = cumsum(Daily_Deaths))
df <- df %>%
  pivot_longer(cols = c(Daily_Cases, Daily_Deaths, Cum_Cases, Cum_Deaths), 
               names_to = "Category")

df$Location <- str_replace_all(df$Location, "_", " ")
df <- df %>% mutate(
  Continent=countrycode(Location,
                        origin = "country.name",
                        destination = "continent"),
  Continent=if_else(Location=="Kosovo", 
                    "Europe", Continent),
  Continent=if_else(Continent == "Oceania", "Asia", Continent),
  Continent=if_else(is.na(Continent), "Other", Continent))
```

# define helper functions

```{r define helper functions}
fun_dot <- function(x) format(x, big.mark = " ",
                              scientific = FALSE,
                              decimal.mark = ".")

# negative in
`%!in%` <- Negate(`%in%`)

# y scale
log10_minor_break = function (...){
  function(x) {
    minx         = floor(min(log10(x), na.rm=T))-1;
    maxx         = ceiling(max(log10(x), na.rm=T))+1;
    n_major      = maxx-minx+1;
    major_breaks = seq(minx, maxx, by=1)
    minor_breaks = 
      rep(log10(seq(1, 9, by=1)), times = n_major)+
      rep(major_breaks, each = 9)
    return(10^(minor_breaks))
  }
}

# for conditionaly filtering
# (from: https://github.com/tidyverse/magrittr/issues/109#issuecomment-371999796)
conditionally <- function(fun){
    function(first_arg, ..., execute){
        if(execute) return(fun(first_arg, ...))
        else return(first_arg)
    }
}
cond_filter <- conditionally(filter)
cond_select <- conditionally(select)
```


# define plot function 

```{r gen plot function, fig.width=16, fig.height=12}
gen_df_to_plot <- function(data, filter_location, null_day_threshold, filter_category) {

  # gen data to plot
  data %>% 
    group_by(Location) %>% 
    filter(Category == filter_category) %>% 
    filter(value >= null_day_threshold) %>% 
    mutate(date_shift=0:(n()-1)/7) %>% # generate date shifted after null_day_threshold
    ungroup(Location) %>% 
    arrange(Location, date_shift) %>% 
    filter(toupper(Location) %in% toupper(filter_location))
    # arrange(Continent, Location, date_shift) %>% 
    # filter(toupper(Location) %in% toupper(filter_location) | Continent %in% filter_location)
}
`%!in%` <- Negate(`%in%`)

gen_plot <- function(data, filter_location,
                     filter_category="Cum_Cases",
                     null_day_threshold=1,
                     emph_color=NULL,
                     proportional=FALSE,
                     n_col=NULL) {
  
  
  df_to_plot <- gen_df_to_plot(data = data,
                               filter_location,
                               filter_category,
                               null_day_threshold = null_day_threshold)
  
  
  df_to_plot$Location_bkg <- df_to_plot$Location
  nr_end <- case_when(null_day_threshold %% 10 == 1 ~ "st ", 
                      null_day_threshold %% 10 == 2 ~ "nd ",
                      null_day_threshold %% 10 == 3 ~ "rd ", 
                      TRUE ~ "th ")
  
  # plot descriptions
  updated_at <- data$dateRep %>% max() %>% format("%b %d")
  
  gg_category <- ifelse(filter_category=="Cum_Deaths", "death", "case")
  if (is.null(emph_color)) emph_color <- ifelse(filter_category=="Cum_Deaths", "black", "red")
  
  
  gg_x_name <- paste0("Weeks past since ", null_day_threshold, nr_end, gg_category) %>%
    tools::toTitleCase()
  gg_caption <- "Code: github.com/avila/corona. Data: https://www.ecdc.europa.eu"
  
  
  if (proportional) {
    df_to_plot <- df_to_plot %>% mutate(value = value / popData2018 * 1e6)
    #threshold <- threshold / 1e5
    y_breaks = 10^(0:9)/1000
    gg_title <- "Evolution of COVID-19 (proportional to population)"
    gg_subtitle <- paste0("Cumulative ", gg_category, "s since ", null_day_threshold, nr_end, gg_category,
                          " (log10 scaled | per million inhabitants | updated ", updated_at, ")") %>%
      tools::toTitleCase()
    
  } else {
    y_breaks = 10^(0:9)
    gg_title <- "Evolution of COVID-19 (absolute numbers)" 
    
    gg_subtitle <- paste0("Cumulative ", gg_category, "s since ", null_day_threshold, nr_end, gg_category,
                          " (log10 scaled | updated ", updated_at, ")") %>%
      tools::toTitleCase()

  }

  # plot
  df_to_plot %>% 
    ggplot(aes(x=date_shift, y=value, group=Location)) +
    geom_line(data=df_to_plot[, c("date_shift", "value", "Location_bkg")],
              aes(x=date_shift, y=value, group=Location_bkg), 
              color="grey") +
    geom_line(color = emph_color) + geom_point(color = emph_color, size=1/2) +
    facet_wrap(~Location, ncol = n_col) +
    
    #title
    labs(title=gg_title, subtitle=gg_subtitle, caption=gg_caption) +
    scale_y_log10(labels=human_num, breaks = y_breaks, minor_breaks=log10_minor_break()) + 
    scale_x_continuous(name=gg_x_name, breaks=seq(0, 1e3, 1), minor_breaks=1:1e3/7)
}
gg_theme <- theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text=element_text(size=rel(1)),
        plot.title = element_text(size=rel(3)),
        plot.subtitle = element_text(size=rel(2)))

human_numbers <- function(x = NULL, smbl ="", signif = 3){
  humanity <- function(y){

    if (!is.na(y)){
      tn <- round(abs(y) / 1e12, signif)
      b <- round(abs(y) / 1e9, signif)
      m <- round(abs(y) / 1e6, signif)
      k <- round(abs(y) / 1e3, signif)
      
      if ( y >= 0 ){
        y_is_positive <- ""
      } else {
        y_is_positive <- "-"
      }
      
      if ( k < 1 ) {
        paste0( y_is_positive, smbl, round(abs(y), signif ))
      } else if ( m < 1){
        paste0 (y_is_positive, smbl,  k , "k")
      } else if (b < 1){
        paste0 (y_is_positive, smbl, m ,"m")
      }else if(tn < 1){
        paste0 (y_is_positive, smbl, b ,"bn")
      } else {
        paste0 (y_is_positive, smbl,  comma(tn), "tn")
      }
    } else if (is.na(y) | is.null(y)){
      "-"
    }
  }
  
  sapply(x,humanity)
}

#' Human versions of large currency numbers - extensible via smbl

human_gbp   <- function(x){human_numbers(x, smbl = "£")}
human_usd   <- function(x){human_numbers(x, smbl = "$")}
human_euro  <- function(x){human_numbers(x, smbl = "€")} 
human_num   <- function(x){human_numbers(x, smbl = "")} 
```


```{r}
top12 <- df %>% filter(Category == "Cum_Deaths") %>% 
  arrange(desc(value)) %>% pull(Location) %>% unique() %>% head(12)
top12
```

# plot proportional to population size 

```{r proportional, fig.width=14, fig.height=20, warning=F, message=F}

filter_countries <- c("Brazil", "Germany", "Italy", "South Korea", 
                      "Spain", "France", "Iran", "Japan", "Singapore",
                      "India", "United states of america", "United kingdom", 
                      "Russia", "Chile", "Colombia", "Portugal", "Ecuador", "South Africa" ,
                      "Belarus", "Sweden", "Netherlands", "Belgium", "Germany", "Switzerland",
                      "Turkey" )
categs <- c("Cum_Deaths", "Cum_Cases")[1:2]
for (cat in categs) {
  threshold <- ifelse(cat=="Cum_Cases", 100, 5 )
  
  p <- gen_plot(df,
                filter_location = filter_countries,
                null_day_threshold = threshold, 
                filter_category = cat,
                proportional = F,
                n_col=4) + 
    gg_theme + theme(strip.text = element_text(size=16))
    
  print(p)
}
```


# plot for selected countries

```{r fig selected countries, fig.width=10, fig.height=16, warning=F, message=F}
filter_countries <- c("Brazil", "Germany", "Italy", "South Korea", 
                      "Spain", "France", "Iran", "Japan", "Singapore",
                      "India", "United states of america", "United kingdom", 
                      "Russia", "Chile", "Colombia", "Portugal", "Ecuador", "South Africa")

for (cat in c("Cum_Cases", "Cum_Deaths")) {
  threshold <- ifelse(cat=="Cum_Cases", 100, 1 )
  
  p <- gen_plot(df, filter_location = filter_countries, emph_color = "red", 
           null_day_threshold = threshold, 
           filter_category = cat, n_col=3) + 
    gg_theme + theme(strip.text = element_text(size=16))
  print(p)
}
```

# plot for selected continents 

```{r fig continents, fig.width=12, fig.height=24, warning=F, message=F}
conts <- unique(df$Continent)[1:4]
conts <- "Europe"
for (cat in c("Cum_Cases", "Cum_Deaths")) {
  threshold <- ifelse(cat=="Cum_Cases", 100, 1 )
  for (cont in conts) {
    p <- gen_plot(df,
                  filter_location = cont,
                  emph_color = "red", 
                  null_day_threshold = threshold, 
                  filter_category = cat, n_col = 4) +
      gg_theme +
      theme(strip.text = element_text(size=16))
    print(p)
  }
}
```




