---
title: "Visualisation of evolution of novel coronavirus"
author: "Marcelo Avila"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# for dates in english 
sys_time_local_old <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "en_US.UTF-8")

# avoid scientific notation
options(scipen = 999)
```

# load libraries

```{r libs, include=FALSE}
library(tidyverse)
library(ggsci)
library(countrycode)
library(readxl)
library(httr)
```

# load data 

```{r}
url <- paste("https://www.ecdc.europa.eu/sites/default/files/documents/",
             "COVID-19-geographic-disbtribution-worldwide-",
             format(Sys.time(), "%Y-%m-%d"), ".xlsx", sep = "")

#download the dataset from the website to a local temporary file
GET(url, authenticate(":", ":", type="ntlm"),
    write_disk(tf <- tempfile(fileext = ".xlsx", pattern = "covid_")))

#read the Dataset sheet into “R”
df <- read_excel(tf)
```


```{r data, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
url_path <- "https://covid.ourworldindata.org/data/full_data.csv"
# df <- readr::read_csv(url_path) %>%
#   pivot_longer(-c(location, date), names_to = "category") %>% 
#   mutate(value = if_else(is.na(value), 0, value))
# 
# pop_data <- readr::read_csv("../data/pop_data.csv",
#                             #locale = locale(grouping_mark = "."),
#                             col_types = cols(Density = col_skip(), 
#                                              GrowthRate = col_skip(),
#                                              WorldPercentage = col_skip(), 
#                                              area = col_skip(),
#                                              dropdownData = col_skip(), 
#                                              rank = col_skip()))
# 
# df <- left_join(df, pop_data, by = c("location"="name")) %>%
#   mutate(pop2020 = pop2020 * 1e3, 
#          value_per_100k_inhab = value / pop2020 * 1e5)
```

```{r relabel}
cat_labels <- c("daily cases", "daily deaths",
                "cumulative cases", "cumulative deaths")
df <- df %>% mutate(category = factor(category, 
                                      labels = cat_labels), 
                    continent=countrycode(location,
                                          origin = "country.name",
                                          destination = "continent"))
if (interactive()) write_csv(df, "../data/our_world_in_data_corona.csv")
```



There is data for `r df$location %>% unique %>% length - 2` countries. 
The last update was on `r tail(df$date, 1) %>% format("%d of %B")`

```{r inspect}
df
```


```{r functions}
# for thousand separator for plotting
fun_dot <- function(x) format(x, big.mark = " ",
                              scientific = FALSE,
                              decimal.mark = ".")

# negative in
`%!in%` <- Negate(`%in%`)

# y scale
log10_minor_break = function (...){
  function(x) {
    minx         = floor(min(log10(x), na.rm=T))-1;
    maxx         = ceiling(max(log10(x), na.rm=T))+1;
    n_major      = maxx-minx+1;
    major_breaks = seq(minx, maxx, by=1)
    minor_breaks = 
      rep(log10(seq(1, 9, by=1)), times = n_major)+
      rep(major_breaks, each = 9)
    return(10^(minor_breaks))
  }
}

calc_cagr <- function(ending, beginning, nr_periods) {
  return((ending / beginning)^(1/nr_periods))-1
}
```


# Cumulative Cases for Selected Countries

```{r, warning=FALSE}
sel_category <- "cumulative cases"  # new cases, new deaths,
                                    # cumulative cases, cumulative deaths
selected_countries <- c("Germany",
                        "Italy",
                        "United Kingdom",
                        "Brazil",
                        "China",
                        "Spain",
                        "South Korea", 
                        "United States")

df %>% 
  # wrangle
  filter(location %in% selected_countries, category==sel_category) %>% 
  mutate(
    location=fct_reorder2(location, date, value),
    label = ifelse(date == "2020-02-29", #max(date),
                        as.character(location), 
                        NA_character_)) %>% 

  # plot
  ggplot(aes(x=date, y=value, color=location)) + 
  geom_point(aes(shape="o")) +
  geom_line(aes(linetype=location)) + 
  
  # labels
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = -1, nudge_y = 1/10,
                            na.rm = TRUE) +
  # legend and scales
  scale_y_log10(name="(log scale)", labels=fun_dot, 
                breaks=10^(0:9),
                #minor_breaks=log10_minor_break()
                minor_breaks=(1 * 1.33333^(0:10000))
                ) + 
  scale_x_date(date_breaks = "1 week", 
               date_labels="%d%b") +
  ggsci::scale_color_aaas() +
  theme(legend.position = "none", 
        axis.title.y = element_blank()) 
```


# Normalized comparison 

```{r}
df$continent %>% unique()
df$category %>% unique() %>% as.character()
```

```{r eval=FALSE, include=FALSE}
sel_continent = "Asia"
sel_category = "cumulative cases"
threshold <- 10
singular_category <- scan(text = sel_category, what = "", quiet=TRUE)[2] %>% 
  substr(1, nchar(.)-1)

df %>%
  filter(category == sel_category, 
         continent == sel_continent) %>% 
  group_by(location) %>% 
  filter(value>=threshold) %>% 
  mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
  ungroup(location) %>% 
  arrange(date_shift) %>% 
  # mutate for legend ordering and ggrepel postioning
  mutate(location=fct_reorder2(location, date_shift, value), 
         # for ggrepel
         label = ifelse(date == max(date),
                        as.character(location), 
                        NA_character_)) %>% 
  ggplot(aes(x=date_shift, y=value, colour=location)) + 
  # geoms
  geom_point() +
  geom_line(aes(linetype=location)) + 
  
  # ggrepel 
  ggrepel::geom_label_repel(aes(label = label),
                            nudge_x = 0,
                            na.rm = TRUE) +
 
  # legend and scales
  scale_y_log10(
    name = paste(sel_category, "(log scale)"), labels=fun_dot, 
    breaks = 10^(0:9),
    minor_breaks=log10_minor_break()) + 
  scale_x_continuous(
    name = paste0("Days past ", threshold, "th ", singular_category),
    breaks = seq(0, 1e5, 7),
    minor_breaks = 1:1e3) +
  scale_color_grey(start = 0, end = .3) +
  
  theme(legend.position = "none", 
        axis.title.y = element_blank()) + 
  #title
  ggtitle(paste("Evolution of novel coronavirus in", sel_continent), 
          subtitle = paste(sel_category, "(log scale)"))

```

```{r def make plot}
make_plot <- function(dta, sel_category="cumulative cases",
                      sel_continent="Europe",
                      sel_country=NULL, 
                      threshold=100) {
  
  # extract singular form of category
  singular_category <- scan(text = sel_category, what = "", quiet=TRUE)[2] %>% 
    substr(1, nchar(.)-1)
  
  sel_plot_title <- ifelse(length(sel_continent)>1,
                                yes = "selected continents",
                                no = sel_continent)

  if (!is.null(sel_country)) {
    dta <- dta %>% filter(location %in% sel_country)
    sel_continent <- unique(dta$continent)
    
    sel_plot_title <- ifelse(length(sel_country)>1,
                             yes = "selected countries",
                             no = sel_country)
  }
  
  
  dta %>% 
    filter(category == sel_category, 
           continent %in% sel_continent) %>% 
    group_by(location) %>% 
    filter(value>=threshold) %>% 
    mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
    ungroup(location) %>% 
    arrange(date_shift) %>% 
    # mutate for legend ordering and ggrepel postioning
    mutate(location=fct_reorder2(location, date_shift, value), 
           # for ggrepel
           label = ifelse(date == max(date),
                          as.character(location), 
                          NA_character_)) %>%
    # plot  
    ggplot(aes(x=date_shift, y=value, colour=location)) + 
    # geoms
    geom_point() +
    geom_line(aes(linetype=location, colour=location)) + 
    #scale_color_grey(start = 0, end = .3) +
    
    # ggrepel 
    ggrepel::geom_label_repel(
      aes(label = label), nudge_x = 1, na.rm = TRUE) +
    
    # legend and scales
    scale_y_log10(
      name = paste(sel_category, "(log scale)"),
      labels=fun_dot, breaks = 10^(0:9), minor_breaks=log10_minor_break()) + 
    scale_x_continuous(
      name = paste0("Days past since ", threshold, "th ", singular_category),
      breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) +
    
    theme(legend.position = "none", axis.title.y = element_blank()) + 
    #title
    ggtitle(paste("Evolution of novel coronavirus in", sel_plot_title), 
            subtitle = paste(sel_category, "(log scale)"))
}
```

```{r plots interactive}
countries <- c("Brazil", "United States", "Italy", "Iran", "South Korea",
               "Singapore", "Japan", "Australia", "India", "Germany", "Spain",
               "Portugal", "Switzerland", "Serbia", "France")
assertthat::are_equal(1, mean(countries %in% df$location))
#countries <- df$location %>% unique
conts <- "Europe"
df_bkg <- df[, c("date", "location", "value")] %>% rename(location2 = location)
p1 <- make_plot(df,
                sel_country = countries,
                sel_continent = NA,
                threshold = 100,
                sel_category = "cumulative cases")
p1 
```


```{r wrap, fig.width=12, fig.height=12}
sel_category <- "cumulative cases"
sel_continent <- "Europe"
threshold <- 25
sel_country <- NULL

# updated
updated_on <- df$date %>% max()
# extract singular form of category
singular_category <- scan(text = sel_category, what = "", quiet=TRUE)[2] %>% 
  substr(1, nchar(.)-1)

sel_plot_title <- ifelse(length(sel_continent)>1,
                         yes = "selected continents",
                         no = sel_continent)

if (!is.null(sel_country)) {
  dta <- dta %>% filter(location %in% sel_country)
  sel_continent <- unique(dta$continent)
  
  sel_plot_title <- ifelse(length(sel_country)>1,
                           yes = "selected countries",
                           no = sel_country)
}

df_p1 <- df %>% 
  filter(category == sel_category, 
         continent %in% sel_continent) %>% 
  group_by(location) %>% 
  filter(value>=threshold) %>% 
  mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
  ungroup(location) %>% 
  arrange(date_shift)
df_p1$location_2 <- df_p1$location
df_p1 %>% 
  ggplot(aes(x = date_shift, y = value, group=location)) +
  geom_line(data = df_p1[, c("date_shift", "value", "location_2")],
            aes(x=date_shift, y=value, group=location_2), colour = "grey") +
  geom_line(color="red") +
  facet_wrap(~location) +
  scale_y_log10() +
  # legend and scales
  scale_y_log10(
    name = paste(sel_category, "(log scale)"),
    labels=fun_dot, breaks = 10^(0:9), minor_breaks=log10_minor_break()) + 
  scale_x_continuous(
    name = paste0("Days past since ", threshold, "th ", singular_category),
    breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) +
  
  theme(legend.position = "none", axis.title.y = element_blank()) + 
  #title
  ggtitle(paste("Evolution of novel coronavirus in", sel_plot_title), 
          subtitle = paste(sel_category, "(log scale)"))


```



```{r opentable case, warning=F}
df_dates <- read_csv("../data/threshold_dates.csv")
df_restaurant <- read_csv("../data/state_of_industry_data.csv") %>%
  pivot_longer( -c(Type, Name), names_to = "Date", values_to = "Value") %>% 
  mutate(Date = as.Date(Date, format="%m/%d"))

df_join <- full_join(df_restaurant, df_dates, 
                     by=c(Name="location")) %>% 
  filter(Name != "Global", category == "cumulative deaths") %>%
  mutate(xx = as.integer(Date - th_5)) %>% 
  group_by(Name) %>% 
  mutate(label = ifelse(xx == max(xx),
                        paste(as.character(Name), Value), 
                        NA_character_)) %>% 
  filter(xx >= 0)

df_join %>% 
  ggplot(aes(x=xx, y=Value, colour=Name)) +
  geom_line(aes(linetype=Name)) + 
  geom_point(aes(shape=Name)) +
  
  ggtitle("Reastaurant Reservations (% Year-over-year variation)",
          "OpenTable data (https://www.opentable.com/state-of-industry)") +
  theme(legend.position = "none", 
        axis.title.y = element_blank()) + 
  scale_x_continuous(
    name = paste0("Days past since ", "5th ", "death"),
    breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) + 
    ggrepel::geom_label_repel(
      aes(label = label), nudge_x = 1, na.rm = TRUE)

```

```{r, fig.width=8, fig.height=8}
df_ot <- read_csv("../data/state_of_industry_data.csv") %>%
  pivot_longer( -c(Type, Name), names_to = "Date", values_to = "Value") %>% 
  mutate(Date = as.Date(Date, format="%m/%d"))

countries1 <- c("Germany", "United States", "United Kingdom", "Global")
countries2 <- c("Mexico", "Ireland", "Canada", "Australia")

df_ot <- df_ot %>% mutate(
  Group = case_when(Name %in% countries1 ~ 1,
                    Name %in% countries2 ~ 2))
updated_on <- df_ot$Date %>% max()

plot <- df_ot %>% filter(Group %in% 1:2) %>% 
  ggplot(aes(x = Date, y = Value, color=Value)) + 
  geom_line(show.legend = F) + geom_point() +
  theme(legend.position = "none", 
        axis.title=element_blank()) + 
  scale_y_continuous(breaks = seq(-100, 0, by = 20)) +
  scale_x_date(breaks="1 week", minor_breaks = "day",date_labels = "%b %d") +
  
  
  labs(title = "Effect on Reastaurant Reservations",
       subtitle = paste0("Year-over-year Percentage Change (Updated on : ", updated_on, ")"), 
       caption = "Data source: https://www.opentable.com/state-of-industry") +
  geom_text(aes(label = Value), nudge_y=-13, nudge_x = -1/3, size=2.2) +
  facet_wrap(~Name, ncol=2)

print(plot)
```

```{r opentable death, warning=F}

df_join <- full_join(df_restaurant, df_dates, 
                     by=c(Name="location")) %>% 
  filter(Name != "Global", category == "cumulative cases") %>%
  mutate(xx = as.integer(Date - th_50)) %>% 
  group_by(Name) %>% 
  mutate(label = ifelse(xx == max(xx),
                        paste(as.character(Name), Value), 
                        NA_character_)) %>% 
  filter(xx >= 0)

df_join %>% 
  ggplot(aes(x=xx, y=Value, colour=Name)) +
  geom_line(aes(linetype=Name)) + 
  geom_point(aes(shape=Name)) +
  
  ggtitle("Reastaurant Reservations (% Year-over-year variation)",
          "OpenTable data (https://www.opentable.com/state-of-industry)") +
  theme(legend.position = "none", 
        axis.title.y = element_blank()) + 
  scale_x_continuous(
    name = paste0("Days past since ", "50th ", "case"),
    breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) + 
    ggrepel::geom_label_repel(
      aes(label = label), nudge_x = 1, na.rm = TRUE)
```

```{r within germany, warning=F, fig.height=7, fig.width=7, message=F}
df_de <- read_csv("../data/COVID_19_de_wiki.csv")
update <- max(df_de$Date)
threshold <- 1
df_de$state_2 <- df_de$state
df_plot <- df_de %>% 
  group_by(state) %>% 
  filter(value>=threshold) %>% 
  mutate(date_shift=0:(n()-1)) %>% # generate date shifted after threshold
  ungroup(state) %>% 
  arrange(date_shift) %>% 
  # mutate for legend ordering and ggrepel postioning
  mutate(state=fct_reorder2(state, date_shift, value), 
         # for ggrepel
         label = ifelse(Date == max(Date),
                        as.character(state), 
                        NA_character_), 
         emph = if_else(state==sel_state, 1, 0)) 

df_plot %>% 
  # plot  
  ggplot(aes(date_shift, value, group=state)) + 
  # geoms
  geom_line(data=df_plot[, c("date_shift", "value", "state_2")],
            aes(x=date_shift, y=value, group=state_2),
            colour="grey") +
  geom_line(color="red") +

  
  # legend and scales
  scale_y_log10(name = paste("Cumulative cases (log scale)"),
                labels=fun_dot, breaks = 10^(0:9), minor_breaks=log10_minor_break()) + 
  scale_x_continuous(name = paste0("Days past since ", threshold, "th ", "case"),
                     breaks = seq(0, 1e5, 7), minor_breaks = 1:1e3) +
  
  theme(legend.position = "none", axis.title.y = element_blank()) + 
  #title
  ggtitle(paste("Evolution of COVID-19 cases in Germany"), 
          paste0("Cumulative cases (log scale, updated: ", update, ")")) + 
  facet_wrap(~state, ncol=4)
```

